language: generic

dist: bionic

## Uncomment the following lines if you require extra dependencies
#before_install:
# - sudo apt-get install ghostscript # If you use latex > dvips > ps2pdf
# - sudo apt-get install python-pygments # If you use the minted package
  # If you use custom fonts:
# - mkdir $HOME/.fonts
# - cp -a $TRAVIS_BUILD_DIR/src/fonts/. $HOME/.fonts/
# - fc-cache -f -v

install:
  - source ./texlive/texlive_install.sh

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

# Change working directory so including files will work
script:
  - cd "$TRAVIS_BUILD_DIR/61.03 - Analisis II A"
  # Texliveonfly will download packages automatically
  - texliveonfly teorica.tex
  - texliveonfly edo.tex
  - texliveonfly ejercicios-01.tex
  - texliveonfly ejercicios-02.tex
  - texliveonfly ejercicios-03.tex
  # You can use latexmk to automatically handle bibtex and references (recommended)
  # latexmk -pdf main.tex

  # But you could use any other compiler as well instead of latexmk. Example:
  - pdflatex -draftmode -halt-on-error teorica.tex
  - pdflatex -draftmode -halt-on-error edo.tex
  - pdflatex -draftmode -halt-on-error ejercicios-01.tex
  - pdflatex -draftmode -halt-on-error ejercicios-02.tex
  - pdflatex -draftmode -halt-on-error ejercicios-03.tex
#  - bibtex main
#  - pdflatex main.tex
#  - pdflatex main.tex # Compile twice to fix references

  # You can also pass arguments to texliveonfly:
#  - texliveonfly --arguments='-shell-escape' main.tex

## Uncomment the following lines to see the packages installed in travis
#after_script:
#  - export PATH=/tmp/texlive/bin/x86_64-linux:$PATH
#  - tlmgr list --only-installed | grep -oP 'i \K.+?(?=:)'
